/**
 * Lines for the empty-pane state.
 *
 * A fresh pane has nothing to show: the shell has only printed its prompt, and
 * Warp hides that until you actually run something. What fills the gap is one
 * short line, picked once per pane so it stays put instead of flickering on
 * every render.
 *
 * Keep these short. Split panes are narrow; long lines wrap and look wrong.
 */

const GREETINGS: readonly string[] = [
  "Let's get started.",
  "A blank prompt is the best kind.",
  "Nothing running. Everything open.",
  "The shell is listening.",
  "Type something reckless.",
  "Fresh session, clean history.",
  "Ready when you are.",
  "No output yet. That's the point.",
  "A process waits to be spawned.",
  "First command's the hardest.",
  "The cursor blinks. Your move.",
  "Empty buffer. Full potential.",
  "Every pipeline starts somewhere.",
  "Just you and the machine.",
  "Say the word.",
  "Quiet terminal, loud ideas.",
  "This pane has no opinions yet.",
  "Warm shell, cold start.",
  "Scrollback is empty. Enjoy it.",
  "No jobs in the background. Yet.",
  "The prompt doesn't judge.",
  "Pick a directory. Commit later.",
  "Stdout is patient.",
  "One keystroke from chaos.",
  "History starts now.",
  "No aliases can save you.",
  "A clean exit is optional.",
  "The path is set. You aren't.",
  "Shell open. Agenda closed.",
  "Permissions granted. Now what?",
  "Nothing to kill or debug.",
  "Tab-complete when you're ready.",
  "cwd awaits a decision.",
  "Zero exit codes so far.",
  "Pipes go both ways. Eventually.",
  "No man page for this moment.",
  "Fork if you must. Just start.",
  "Env loaded. Intent optional.",
  "The prompt rewrote itself.",
  "Still no stderr. Relish that.",
  "A nameless pane is still a pane.",
  "Ctrl+C is always an option.",
  "Session zero. Make it count.",
  "The shell forgot last week.",
  "No processes, no drama.",
  "Type the command you'll regret.",
  "Idle is a valid state.",
  "Your $PATH is longer than this.",
  "Nothing compiled. Nothing broke.",
  "The tty is yours exclusively.",
  "Signals are quiet. For now.",
  "Blank line theory in practice.",
  "You can always split later.",
  "The machine has no plans either.",
  "Exit status still undefined.",
  "No diffs. No commits. No rush.",
  "Prompt ready. Ego optional.",
  "Somewhere a Makefile is watching.",
  "Don't overthink the first line.",
  "Shell builtins only need one shot.",
  "No cargo cult required.",
  "The filesystem ignores vibes.",
  "Type slow. It'll wait.",
  "Unattached and unbothered.",
  "A new pane is a soft reset.",
  "Nobody's reading this but you.",
  "Command not found. Yet.",
  "Cursor knows more than it says.",
  "Room for a long-running job.",
  "Stack traces start with a choice.",
  "No websocket drama in here.",
  "Just you, $HOME, and a blink.",
  "The quiet before the build.",
  "Stderr has nothing to report.",
  "A process tree of one.",
  "Keep it under eighty columns.",
  "No tmux to reattach. Fresh.",
  "The shell already forgave you.",
  "Start with ls. End with regret.",
  "No CI watching this pane.",
  "Localhost is still listening.",
  "Context is yours. Prompt is ours.",
  "Nothing stuck in a pipe.",
  "The next character is hardest.",
  "Whitespace counts. Be careful.",
  "A terminal with no story yet.",
  "Run something small first.",
  "No open files. No open questions.",
  "Clock running. Shell isn't.",
  "If in doubt, echo hello.",
  "Dead simple is still simple.",
  "This is the last quiet second.",
  "No args. No flags. No excuses.",
  "Shorter than your TODO list.",
  "Something will print. Eventually.",
  "cwd is a suggestion until you cd.",
  "Nobody pipes into an empty mind.",
  "Free file descriptors for all.",
  "You can always grep later.",
  "The shell doesn't do pep talks.",
  "No dangling pointers here.",
  "Hit enter when it feels right.",
  "stdin is open. Your move.",
  "Silent, but ready.",
  "Don't name it until it works.",
  "sudo is only a few keys away.",
  "No lockfile. No drama.",
  "Rebase later. Type now.",
  "Your shell rc already ran.",
  "Nothing blocked on I/O yet.",
  "The boring command is right.",
  "No panic from a blank line.",
  "Clean process group inherited.",
  "Delete is permanent. Start isn't.",
  "The pager has nothing to page.",
  "Stay in $HOME to think.",
  "No hanging parentheses. Yet.",
  "A job without a number still runs.",
  "Shebang optional. Ambition too.",
  "The network is fine. Probably.",
  "No rustc. Fans are grateful.",
  "Write once. Redirect twice.",
  "Your last pane can't see this one.",
  "EOF is a long way off.",
  "Default shell. Default you.",
  "No debugger tabs open. Good.",
  "Type the command you already know.",
  "Permission denied can wait.",
  "A cold buffer, a warm keyboard.",
  "No stack overflow. Either kind.",
  "You can still walk away.",
  "Cheap syscalls until they aren't.",
  "The prompt is the whole UI.",
  "No zombie children. Keep it so.",
  "When in doubt, pwd.",
  "A pane is a promise of output.",
  "Last command never ran. Perfect.",
  "Don't optimize the untyped.",
  "No shared memory. No shared blame.",
  "Shell started without you.",
  "Room temperature CPU. For now.",
  "All signals caught. None thrown.",
  "Your next typo hasn't happened.",
  "No remote. No origin. Just here.",
  "Simple is still a command.",
  "Scroll wheel idle. For now.",
  "Nothing to detach from.",
  "A clean slate with a blink.",
  "This idea won't outlast the shell.",
  // --- AI / vibecoding / slop ---
  "One man's slop is another man's gold.",
  "Vibecode first. Refactor never.",
  "Ship the slop. Polish is optional.",
  "Prompted into existence.",
  "The model wrote this. Almost.",
  "Accept all. Ask questions later.",
  "LGTM from an LLM is still LGTM.",
  "Hallucinated, then fixed. Classic.",
  "Trust the vibe. Verify the types.",
  "Slop that compiles is still code.",
  "Autocompleted into production.",
  "Copilot blinked first.",
  "Generate, run, regret, repeat.",
  "No human wrote this path. Yet.",
  "The AI is waiting on you now.",
  "Prompt engineering is just typing.",
  "Vibes are green. Tests are red.",
  "Ship it before the context fills.",
  "Token budget infinite. Taste finite.",
  "This repo has seen worse slop.",
  "Paste the stack trace into chat.",
  "Agentic, not magic.",
  "The diff is larger than the idea.",
  "Review the agent. Trust nothing.",
  "Slop today. Senior tomorrow.",
  "It works on the model's machine.",
  "Undo is your best collaborator.",
  "A green check from silicon.",
  "Don't commit the first draft.",
  "The autocomplete knows your secrets.",
  "Vibe-coded at 2am. Ship at 9.",
  "No comments. The AI forgot them.",
  "Context window full of hope.",
  "Ask the model. Blame the model.",
  "Zero-shot into production.",
  "The agent opened too many files.",
  "Synthetic code. Real bugs.",
  "Prompt, patch, pray.",
  "This variable was named by AI.",
  "Slop in, gold out. Sometimes.",
  "The LLM already tried that.",
  "Generated with confidence. Wrong.",
  "Pair with a model. Keep the veto.",
  "Yolo mode is a lifestyle.",
  "Fewer tokens. Better taste.",
  "The agent wants another tool call.",
  "AI wrote it. You own it.",
  "No, the model can't ssh for you.",
  "Vibes peak before the build fails.",
  "Refuse the first three suggestions.",
  "This function has AI fingerprints.",
  "Slop is a spectrum, not a binary.",
  "The prompt was longer than the fix.",
  "Agent said done. Tests said no.",
  "Hot-reloaded into delusion.",
  "Code review by gut feeling.",
  "The model invented that API.",
  "Ship the demo. Hide the source.",
  "Your coauthor has no GitHub.",
  "Tab-accepted into destiny.",
  // --- intentionally cheesy ---
  "Dream big. Compile bigger.",
  "Believe in your stack.",
  "You and the model vs the world.",
  "Main character energy: enabled.",
  "Today's the day you ship.",
  "Manifest the green build.",
  "Your potential is unbounded.",
  "Slop with purpose. Code with heart.",
  "Rise and grind... the build.",
  "The universe wants this merge.",
  "You're not debugging. You're growing.",
  "Hustle culture, but for terminals.",
  "That bug fears your prompt.",
  "Live laugh ls.",
  "Good vibes only. Strict mode off.",
  "You got this. The agent got this.",
  "Touch grass? Touch production.",
  "Be the change you want to deploy.",
  "Success is just git push -f away.",
  "Glow up: from idea to npm publish.",
  // --- funny AI / vibecoder / slop ---
  "The model said it was done. Twice.",
  "Slop so good it almost works.",
  "I didn't write this. I approved it.",
  "Vibecoder by day. Debugger by night.",
  "This code has never met a human.",
  "Prompted at 3am. Still broken at 4.",
  "The agent gaslit my tests.",
  "Slop residual in the diff.",
  "It compiled. I'm calling that a win.",
  "My coauthor is a probability cloud.",
  "Please clap for this generated PR.",
  "The AI refactored my career.",
  "LGTM means Looks Generated To Me.",
  "This bug was invented, not found.",
  "Context window full of excuses.",
  "I outsourced my imposter syndrome.",
  "The model is confident. Wrong, but.",
  "Ship the slop before it cools.",
  "No thoughts. Just tool calls.",
  "Autocompleted my way into this mess.",
  "The agent opened 47 files. Why.",
  "Slop artisan. Handmade with tokens.",
  "I pair program with a slot machine.",
  "This function dreams of being real.",
  "Vibe check failed. Force pushed.",
  "The LLM named it utils2. Final.",
  "I am become slop, destroyer of clean.",
  "It said 'you're absolutely right.'",
  "Zero tests. Infinite confidence.",
  "My stack is vibes all the way down.",
  // --- generic AI assistant phrases ---
  "You're absolutely right.",
  "Great question!",
  "Let me break that down.",
  "Of course! Happy to help.",
  "Here's a simple approach.",
  "That makes total sense.",
  "I understand your frustration.",
  "Let's take a step back.",
  "Good catch!",
  "I've updated the code.",
  "Does that make sense?",
  "Let me know if you need anything else!",
  "As an AI, I can't...",
  "I'll be honest with you.",
  "Here's what I'd recommend.",
  "That's a common gotcha.",
  "You're on the right track.",
  "Let me rethink that.",
  "I may have been wrong earlier.",
  "Would you like me to explain?",
  "I've fixed the issue.",
  "Sorry about that!",
  "Here's a cleaner version.",
  "In short:",
  "Happy to dig deeper.",
  "That should do it!",
];

/** One greeting, chosen at random. */
export function randomGreeting(): string {
  return GREETINGS[Math.floor(Math.random() * GREETINGS.length)] ?? GREETINGS[0];
}
