import { createCooldownPicker as createHalfCooldownPicker } from "./cooldownPicker";

/**
 * Lines for the empty-pane state.
 *
 * A fresh pane has nothing to show: the shell has only printed its prompt, and
 * Warp hides that until you actually run something. What fills the gap is one
 * short line, picked once per pane so it stays put instead of flickering on
 * every render.
 *
 * Keep these short. Split panes are narrow; long lines wrap and look wrong.
 */

const GREETINGS: readonly string[] = [
  "Let's get started.",
  "A blank prompt is the best kind.",
  "Nothing running. Everything open.",
  "The shell is listening.",
  "Type something reckless.",
  "Fresh session, clean history.",
  "Ready when you are.",
  "No output yet. That's the point.",
  "A process waits to be spawned.",
  "First command's the hardest.",
  "The cursor blinks. Your move.",
  "Empty buffer. Full potential.",
  "Every pipeline starts somewhere.",
  "Just you and the machine.",
  "Say the word.",
  "Quiet terminal, loud ideas.",
  "This pane has no opinions yet.",
  "Warm shell, cold start.",
  "Scrollback is empty. Enjoy it.",
  "No jobs in the background. Yet.",
  "The prompt doesn't judge.",
  "Pick a directory. Commit later.",
  "Stdout is patient.",
  "One keystroke from chaos.",
  "History starts now.",
  "No aliases can save you.",
  "A clean exit is optional.",
  "The path is set. You aren't.",
  "Shell open. Agenda closed.",
  "Permissions granted. Now what?",
  "Nothing to kill or debug.",
  "Tab-complete when you're ready.",
  "cwd awaits a decision.",
  "Zero exit codes so far.",
  "Pipes go both ways. Eventually.",
  "No man page for this moment.",
  "Fork if you must. Just start.",
  "Env loaded. Intent optional.",
  "The prompt rewrote itself.",
  "Still no stderr. Relish that.",
  "A nameless pane is still a pane.",
  "Ctrl+C is always an option.",
  "Session zero. Make it count.",
  "The shell forgot last week.",
  "No processes, no drama.",
  "Type the command you'll regret.",
  "Idle is a valid state.",
  "Your $PATH is longer than this.",
  "Nothing compiled. Nothing broke.",
  "The tty is yours exclusively.",
  "Signals are quiet. For now.",
  "Blank line theory in practice.",
  "You can always split later.",
  "The machine has no plans either.",
  "Exit status still undefined.",
  "No diffs. No commits. No rush.",
  "Prompt ready. Ego optional.",
  "Somewhere a Makefile is watching.",
  "Don't overthink the first line.",
  "Shell builtins only need one shot.",
  "No cargo cult required.",
  "The filesystem ignores vibes.",
  "Type slow. It'll wait.",
  "Unattached and unbothered.",
  "A new pane is a soft reset.",
  "Nobody's reading this but you.",
  "Command not found. Yet.",
  "Cursor knows more than it says.",
  "Room for a long-running job.",
  "Stack traces start with a choice.",
  "No websocket drama in here.",
  "Just you, $HOME, and a blink.",
  "The quiet before the build.",
  "Stderr has nothing to report.",
  "A process tree of one.",
  "Keep it under eighty columns.",
  "No tmux to reattach. Fresh.",
  "The shell already forgave you.",
  "Start with ls. End with regret.",
  "No CI watching this pane.",
  "Localhost is still listening.",
  "Context is yours. Prompt is ours.",
  "Nothing stuck in a pipe.",
  "The next character is hardest.",
  "Whitespace counts. Be careful.",
  "A terminal with no story yet.",
  "Run something small first.",
  "No open files. No open questions.",
  "Clock running. Shell isn't.",
  "If in doubt, echo hello.",
  "Dead simple is still simple.",
  "This is the last quiet second.",
  "No args. No flags. No excuses.",
  "Shorter than your TODO list.",
  "Something will print. Eventually.",
  "cwd is a suggestion until you cd.",
  "Nobody pipes into an empty mind.",
  "Free file descriptors for all.",
  "You can always grep later.",
  "The shell doesn't do pep talks.",
  "No dangling pointers here.",
  "Hit enter when it feels right.",
  "stdin is open. Your move.",
  "Silent, but ready.",
  "Don't name it until it works.",
  "sudo is only a few keys away.",
  "No lockfile. No drama.",
  "Rebase later. Type now.",
  "Your shell rc already ran.",
  "Nothing blocked on I/O yet.",
  "The boring command is right.",
  "No panic from a blank line.",
  "Clean process group inherited.",
  "Delete is permanent. Start isn't.",
  "The pager has nothing to page.",
  "Stay in $HOME to think.",
  "No hanging parentheses. Yet.",
  "A job without a number still runs.",
  "Shebang optional. Ambition too.",
  "The network is fine. Probably.",
  "No rustc. Fans are grateful.",
  "Write once. Redirect twice.",
  "Your last pane can't see this one.",
  "EOF is a long way off.",
  "Default shell. Default you.",
  "No debugger tabs open. Good.",
  "Type the command you already know.",
  "Permission denied can wait.",
  "A cold buffer, a warm keyboard.",
  "No stack overflow. Either kind.",
  "You can still walk away.",
  "Cheap syscalls until they aren't.",
  "The prompt is the whole UI.",
  "No zombie children. Keep it so.",
  "When in doubt, pwd.",
  "A pane is a promise of output.",
  "Last command never ran. Perfect.",
  "Don't optimize the untyped.",
  "No shared memory. No shared blame.",
  "Shell started without you.",
  "Room temperature CPU. For now.",
  "All signals caught. None thrown.",
  "Your next typo hasn't happened.",
  "No remote. No origin. Just here.",
  "Simple is still a command.",
  "Scroll wheel idle. For now.",
  "Nothing to detach from.",
  "A clean slate with a blink.",
  "This idea won't outlast the shell.",
  // --- AI / vibecoding / slop ---
  "One man's slop is another man's gold.",
  "Vibecode first. Refactor never.",
  "Ship the slop. Polish is optional.",
  "Prompted into existence.",
  "The model wrote this. Almost.",
  "Accept all. Ask questions later.",
  "LGTM from an LLM is still LGTM.",
  "Hallucinated, then fixed. Classic.",
  "Trust the vibe. Verify the types.",
  "Slop that compiles is still code.",
  "Autocompleted into production.",
  "Copilot blinked first.",
  "Generate, run, regret, repeat.",
  "No human wrote this path. Yet.",
  "The AI is waiting on you now.",
  "Prompt engineering is just typing.",
  "Vibes are green. Tests are red.",
  "Ship it before the context fills.",
  "Token budget infinite. Taste finite.",
  "This repo has seen worse slop.",
  "Paste the stack trace into chat.",
  "Agentic, not magic.",
  "The diff is larger than the idea.",
  "Review the agent. Trust nothing.",
  "Slop today. Senior tomorrow.",
  "It works on the model's machine.",
  "Undo is your best collaborator.",
  "A green check from silicon.",
  "Don't commit the first draft.",
  "The autocomplete knows your secrets.",
  "Vibe-coded at 2am. Ship at 9.",
  "No comments. The AI forgot them.",
  "Context window full of hope.",
  "Ask the model. Blame the model.",
  "Zero-shot into production.",
  "The agent opened too many files.",
  "Synthetic code. Real bugs.",
  "Prompt, patch, pray.",
  "This variable was named by AI.",
  "Slop in, gold out. Sometimes.",
  "The LLM already tried that.",
  "Generated with confidence. Wrong.",
  "Pair with a model. Keep the veto.",
  "Yolo mode is a lifestyle.",
  "Fewer tokens. Better taste.",
  "The agent wants another tool call.",
  "AI wrote it. You own it.",
  "No, the model can't ssh for you.",
  "Vibes peak before the build fails.",
  "Refuse the first three suggestions.",
  "This function has AI fingerprints.",
  "Slop is a spectrum, not a binary.",
  "The prompt was longer than the fix.",
  "Agent said done. Tests said no.",
  "Hot-reloaded into delusion.",
  "Code review by gut feeling.",
  "The model invented that API.",
  "Ship the demo. Hide the source.",
  "Your coauthor has no GitHub.",
  "Tab-accepted into destiny.",
  // --- intentionally cheesy ---
  "Dream big. Compile bigger.",
  "Believe in your stack.",
  "You and the model vs the world.",
  "Main character energy: enabled.",
  "Today's the day you ship.",
  "Manifest the green build.",
  "Your potential is unbounded.",
  "Slop with purpose. Code with heart.",
  "Rise and grind... the build.",
  "The universe wants this merge.",
  "You're not debugging. You're growing.",
  "Hustle culture, but for terminals.",
  "That bug fears your prompt.",
  "Live laugh ls.",
  "Good vibes only. Strict mode off.",
  "You got this. The agent got this.",
  "Touch grass? Touch production.",
  "Be the change you want to deploy.",
  "Success is just git push -f away.",
  "Glow up: from idea to npm publish.",
  // --- funny AI / vibecoder / slop ---
  "The model said it was done. Twice.",
  "Slop so good it almost works.",
  "I didn't write this. I approved it.",
  "Vibecoder by day. Debugger by night.",
  "This code has never met a human.",
  "Prompted at 3am. Still broken at 4.",
  "The agent gaslit my tests.",
  "Slop residual in the diff.",
  "It compiled. I'm calling that a win.",
  "My coauthor is a probability cloud.",
  "Please clap for this generated PR.",
  "The AI refactored my career.",
  "LGTM means Looks Generated To Me.",
  "This bug was invented, not found.",
  "Context window full of excuses.",
  "I outsourced my imposter syndrome.",
  "The model is confident. Wrong, but.",
  "Ship the slop before it cools.",
  "No thoughts. Just tool calls.",
  "Autocompleted my way into this mess.",
  "The agent opened 47 files. Why.",
  "Slop artisan. Handmade with tokens.",
  "I pair program with a slot machine.",
  "This function dreams of being real.",
  "Vibe check failed. Force pushed.",
  "The LLM named it utils2. Final.",
  "I am become slop, destroyer of clean.",
  "It said 'you're absolutely right.'",
  "Zero tests. Infinite confidence.",
  "My stack is vibes all the way down.",
  // --- generic AI assistant phrases ---
  "You're absolutely right.",
  "Great question!",
  "Let me break that down.",
  "Of course! Happy to help.",
  "Here's a simple approach.",
  "That makes total sense.",
  "I understand your frustration.",
  "Let's take a step back.",
  "Good catch!",
  "I've updated the code.",
  "Does that make sense?",
  "Let me know if you need anything else!",
  "As an AI, I can't...",
  "I'll be honest with you.",
  "Here's what I'd recommend.",
  "That's a common gotcha.",
  "You're on the right track.",
  "Let me rethink that.",
  "I may have been wrong earlier.",
  "Would you like me to explain?",
  "I've fixed the issue.",
  "Sorry about that!",
  "Here's a cleaner version.",
  "In short.",
  "Happy to dig deeper.",
  "That should do it!",
  // --- more vibecoding / AI agents ---
  "A slop a day keeps the doctor away.",
  "0% code, 100% vibes.",
  "Make no mistakes.",
  "No think, vibe only.",
  "Time to pretend you are working.",
  "Reading code is for the weak.",
  "What is a variable?",
  "Agent said ship. I said ship.",
  "Tests are a suggestion.",
  "I prompt therefore I am.",
  "Stack overflow? Never heard of her.",
  "This PR was vibed into existence.",
  "No plan, just agents.",
  "Refactor is a four-letter word.",
  "I outsourced my brain cells.",
  "The agent is cooking. Trust.",
  "Syntax is for people who type.",
  "My IDE is just a chat window.",
  "Ship first. Understand never.",
  "Context window is my short-term memory.",
  "Who needs docs when you have vibes.",
  "Copy paste from the future.",
  "The linter is gaslighting me.",
  "Types are optional. Fear is not.",
  "I am the human in the loop. Barely.",
  "Agent swarm go brrr.",
  "This code reviews itself. Allegedly.",
  "npm install confidence.",
  "Breakpoints are for cowards.",
  "The bug is a feature. The model said so.",
  "I pair program with entropy.",
  "git blame the temperature.",
  "No ticket. Just vibes.",
  "Senior engineer? No. Senior prompter.",
  "Production is the real unit test.",
  "My stack is agent all the way down.",
  "Please hold while the model thinks.",
  "Autonomous until it isn't.",
  "I accepted all. All of it.",
  "The diff writes itself. Sort of.",
  "Comment? The agent forgot again.",
  "Works on my context window.",
  "Skill issue. Fixed with more tokens.",
  "This function was born in a chat.",
  "Merge conflict with reality.",
  "The agent opened chrome. Why.",
  "Rubber duck but it codes back.",
  "I don't debug. I re-prompt.",
  "Latency is just dramatic pause.",
  "Tool call spiral loading...",
  "Yolo commit. Yolo deploy.",
  "The model hallucinated CI green.",
  "I hope it doesn't delete my user folder.",
  "This PR was written by committee of one LLM.",
  // --- even more vibecoding ---
  "I don't write code. I commission it.",
  "The agent rewrote main. Again.",
  "I approved a PR I never opened.",
  "Please don't rm -rf anything important.",
  "My IDE is three chats deep.",
  "Tests? The agent pinky-promised.",
  "I asked for a button. Got a framework.",
  "Wait, why is it installing dependencies?",
  "Read the code? That's what models are for.",
  "I tab-accepted my way into tech debt.",
  "The diff is 4k lines. I reviewed zero.",
  "Please clap for this hallucinated API.",
  "I outsourced sleep to the agent.",
  "The model said LGTM to itself.",
  "No design doc. Just good vibes.",
  "Agent said simple. Diff said novel.",
  "This variable is named tmp_final_v3.",
  "The agent deleted the tests. Bold.",
  "We're not debugging. We're negotiating.",
  "I pair with a model that never sleeps.",
  "It works if you don't look closely.",
  "The LLM invented a package. Install denied.",
  "I fixed it by starting a new chat.",
  "The agent opened Docker. Nobody asked.",
  "My coauthor has no coffee breaks.",
  "The model is sorry. The bug remains.",
  "I don't read stack traces. I paste them.",
  "Agent swarm: 12 opinions, 0 tests.",
  "I accepted the rewrite. Both of them.",
  "Production is just staging with witnesses.",
  "The agent wants sudo. Absolutely not.",
  "No ticket. No plan. Only vibes.",
  "I don't debug. I change the prompt slightly.",
  "Did it just rewrite my entire config?",
  "I hope .env stays uncommitted this time.",
  "Why is the agent reading my home directory?",
  "It said 'quick fix' and touched 40 files.",
  "Please don't push without asking me.",
  "I told it to be careful. It used force.",
  "Is that my production database URL?",
  "The agent is running migrate. Cool cool cool.",
  "I only wanted a typo fixed.",
  "Stop opening new terminals. One is enough.",
  "It deleted the feature and kept the bugs.",
  "I hope it remembers which branch we're on.",
  "Why does this need network access?",
  "It renamed everything. Including me, almost.",
  "I asked for help. It rewrote package.json.",
  "Please don't touch the lockfile. Too late.",
  "The agent is 'cleaning up.' Hide the children.",
  "I should have made a backup first.",
  "It force-pushed to main. In my dreams.",
  "Wait, that was the wrong repo.",
  "I hope those were dummy credentials.",
  "It solved the wrong problem correctly.",
  "The agent is looping. Send help.",
  "I said 'small change.' It said 'refactor.'",
  "Please don't install another monorepo tool.",
  "It committed node_modules. Of course it did.",
  "I hope this chat doesn't cost a car.",
  "Why is it rewriting the README unprompted?",
  "It fixed the bug by deleting the feature.",
  "I should read this diff. I won't.",
  "The agent asked for my API key. Nice try.",
  "It is now rewriting the rewrite.",
  // --- random funny nonsense ---
  "Come to Brazil!",
  "I'm running out of phrases.",
  "My brain is turning into mush.",
  "Don't commit your .env file.",
  "I just want to go to New Zeland.",
  "Your eyes are so pretty uwu.",
  "Touch grass. Then touch prod.",
  "This meeting could've been a panic.",
  "I peed a little when it compiled.",
  "Hot single terminal in your area.",
  "Please clap.",
  "Skibidi architecture.",
  "The duck knows what you did.",
  "Hydrate or die-drate.",
  "Error 418: I'm a teapot.",
  "Have you tried turning it off?",
  "Another pane? Bold of you.",
  "It's giving main character shell.",
  "Out of office. In the terminal.",
  "I fear no man. Only merge conflicts.",
  "This is fine. Everything is fine.",
  "Task failed successfully.",
  "Based and shellpilled.",
  "Real ones cd without tab.",
  "Send nudes (of the stack trace).",
  "The cake is a free plan limit.",
  "Sorry Mom, I'm vibecoding again.",
  "I invented this bug on purpose.",
  "Emotional support package.json.",
  "New Zeland still waits for me.",
  "Brazil called. They want you back.",
  // --- more vibe-coded nonsense ---
  "I'm tired boss...",
  "Is Obsidian an IDE?",
  "Is Notion a database?",
  "Is Figma a backend?",
  "Is Discord my CI?",
  "Is ChatGPT my senior?",
  "Is Claude my tech lead?",
  "Is Cursor even real?",
  "Is Markdown Turing complete?",
  "Is JSON a programming language?",
  "Is YAML a personality?",
  "Is linear.app my therapist?",
  "Is the README the architecture?",
  "I'm not stuck. I'm vibe-checking.",
  "Boss, the agent is cooking.",
  "Boss, it almost works.",
  "Boss, I accepted all.",
  "Boss, the types are optional.",
  "Boss, the tests are vibes.",
  "I'm so tired of this diff, boss.",
  "Just one more re-prompt, boss.",
  "The agent fixed it. Trust me boss.",
  "We ship at dawn. Or whenever.",
  "My second brain is a chat log.",
  "Obsidian vault = production mind.",
  "I architected this in a voice note.",
  "The PR description was generated.",
  "I named the branch fix-stuff-final.",
  "It works if you believe hard enough.",
  "Please don't ask how it works.",
  "I learned React from the autocomplete.",
  "Documentation is a vibe, not a file.",
  "I use dark mode for the dopamine.",
  "My design system is good intentions.",
  "The stack is vibes + TypeScript + hopium.",
  "I don't deploy. I manifest.",
  "Can you just make it look nice?",
  "Make it pop. Whatever that means.",
  "Is this production or cosplay?",
  "I'm not a developer. I'm a conductor.",
  "The orchestra is twelve agents deep.",
  "I outsourced sleep. Still tired.",
  "One shot me this whole app.",
  "Zero-shot. Zero understanding.",
  "Few-shot into the abyss.",
  "The model said ship it. I shipped it.",
  "I pair program with my anxiety.",
  "This is fine. The agent said so.",
  "My IDE is a chat with amnesia.",
  "Context cleared. Identity optional.",
  "New chat, same bugs.",
  "I fixed it by starting over. Again.",
  "The plan was vibes. The code is vibes.",
  "I don't write specs. I write prompts.",
  "Architecture decision: yolo.",
  "RFC stands for Really Fancy Chat.",
  "Standup update: still prompting.",
  "Blocker: the model is thinking.",
  "ETA: when the tokens run out.",
  "Priority: vibes. Severity: also vibes.",
  "I'm tired boss... but we cook.",
  "Is VS Code just a browser?",
  "Is the terminal an IDE now?",
  "Is wget a package manager?",
  "Is curl my package manager?",
  "Is Docker just vibes in a box?",
  "Is Kubernetes a lifestyle?",
  "Is git push -f a feature?",
  "Is main protected? Asking for a friend.",
  "I store secrets in my heart. And .env.",
  "My monorepo has one package. Me.",
  "The linter is just jealous.",
  "Prettier formatted my soul.",
  "I configured ESLint by accepting defaults.",
  "Type errors are just suggestions, right?",
  "any is a valid type. Fight me.",
  "I disable strict mode for the culture.",
  "npm run build && pray.",
  "It compiled. Ship it. Run.",
  "Green CI is a love language.",
  "Red CI is character development.",
  "I debug with console.log and hope.",
  "Breakpoints? In this economy?",
  "The bug fears my re-prompt energy.",
  "I asked the duck. The duck shrugged.",
  "Rubber duck but it's Claude.",
  "My mentor is temperature 0.7.",
  "I learned system design from memes.",
  "Is this microservices or micro-vibes?",
  "I scaled horizontally with more agents.",
  "Cache invalidation? I invalidate vibes.",
  "There are only two hard things: naming and agents.",
  "Off-by-one? Off-by-entire-feature.",
  "Works on my machine. The model's machine.",
  "Reproduced in production. Classic.",
  "I hotfixed the hotfix of the hotfix.",
  "Semantic versioning: vibes.major.minor.",
  "Changelog: stuff. Lots of stuff.",
  "Breaking change? Feature, actually.",
  "I migrated by rewriting everything.",
  "Legacy code is last week's chat.",
  "Technical debt is just deferred vibes.",
  "I pay interest in stack traces.",
  "The bus factor is me and the model.",
  "On-call? I'm always on-prompt.",
  "Pager went off. Agent went off.",
  "SRE stands for Somehow Running Everywhere.",
  "I observe nothing. I feel everything.",
  "Metrics are vibes with numbers.",
  "SLO: ship something. Anything.",
  "Error budget: already spent.",
  "Blameless postmortem: the agent did it.",
  "Root cause: Tuesday.",
  "I'm tired boss... send more tokens.",
  // --- Slop Live / vibe-coding extras ---
  "Welcome back to Slop Live!",
  "The Slop Thickens",
  "The slop must flow.",
  "Live from the context window.",
  "Slop Live: now with 40% more confidence.",
  "We're going live with untested code.",
  "In this episode of 'it works locally'…",
  "Breaking news: still broken.",
  "Stay tuned for the next hallucination.",
  "Brought to you by Ctrl+Z.",
  "Viewer discretion: generated code ahead.",
  "Like and subscribe to my stack traces.",
  "This message was approved by vibes.",
  "Don't touch that dial. Touch the agent.",
  "Plot twist: the tests were also slop.",
  "Previously on this codebase…",
  "Next time: we fix the last fix.",
  "Commercial break for npm install.",
  "Audience of one. Energy of ten.",
  "Rated R for Recursive refactors.",
  "Tonight's guest: undefined is not a function.",
  "Call now for free technical debt!",
  "As seen on main.",
  "No refunds on vibes.",
  "Happening now: chaos compilation.",
  "Your regularly scheduled spaghetti.",
  "We now return to your broken build.",
  "Slop thicker than water.",
  "Vibes so loud the linter left.",
  "This pane is brought to you by YOLO.",
  "Ask not what you can code—ask the model.",
  "In a world where tests are optional…",
  "One agent. One dream. Many files.",
  "The empire of slop strikes back.",
  "May the force push be with you.",
  "I have a bad feeling about this PR.",
  "These aren't the bugs you're looking for.",
  "Do or do not. There is no typecheck.",
  "I've got a good feeling about this deploy.",
  "Use the source—or generate it.",
  "Vibe coding: type first, think never.",
  "This is fine. Everything is tokens.",
  "Ship it while the vibe is still warm.",
  "I don't write code. I curate outcomes.",
  "Prompt engineer by day. Survivor by night.",
  "Sponsored by pure delusion.",
  "Please hold for a better answer.",
  "Trust the process. Distrust the process.",
  "The thickens have slopped.",
  "Coming up next: more refactors.",
  "Slop Live never ends. Only restarts.",
  "Tonight on Slop: we ship vibes.",
  "Welcome to the show. The build is the host.",
  "And now, a word from our sponsor: hope.",
  "Cue the confetti. Ignore the red CI.",
  "Live reaction to my own code. Horrified.",
  "We thick the slop so you don't have to.",
  // --- song parodies: pathos / vibecoding / slop / agents / code ---
  "Ducks just wanna have fun.",
  "Never gonna give you up… the build.",
  "Hello from the other side of the merge.",
  "I will always love this green CI.",
  "Sweet child o' mine… and my agents.",
  "Don't stop believing in the compile.",
  "Take on me, take me on-call.",
  "I want it that way: types first.",
  "Oops, I shipped it again.",
  "Smells like team spirit. And slop.",
  "Billie Jean is not my merge request.",
  "All the single tickets, all the single tickets.",
  "We will rock you… after typecheck.",
  "Bohemian rhapsody, no escape from this stack.",
  "Mr. Brightside of the red CI.",
  "Somebody once told me the agent was done.",
  "Wake me up when the deploy finishes.",
  "Losing my religion over this null.",
  "I want to break free of technical debt.",
  "Another one bites the dust… the tests.",
  "Livin' on a prayer and a prompt.",
  "Every breath you take, every test I fake.",
  "Wonderwall of context windows.",
  "Under pressure… of the token limit.",
  "Don't stop me now, I'm vibecoding.",
  "Fix you? No. Fix the types.",
  "Rolling in the deep stack traces.",
  "Shape of you: undefined is not a function.",
  "Bad romance with the linter.",
  "Toxic dependency, baby.",
  "Uptown funk you up… the monorepo.",
  "Can't stop the feeling… of a green build.",
  "Happy? The tests say maybe.",
  "You belong with me… and my merge conflicts.",
  "Blank space—where the docs should be.",
  "We are never ever getting back together… with that bug.",
  "Style: race condition. Style: ship it.",
  "Dance monkey, dance agent.",
  "Blinding lights on production.",
  "Levitating over the stack overflow.",
  "As it was… broken in main.",
  "Anti-hero of my own codebase.",
  "Cruel summer of deploys.",
  "Flowers? No. Just stack traces.",
  "Espresso-powered agent loop.",
  "Please please please pass CI.",
  "I ain't worried… the agent is.",
  "Unwritten: the commit message.",
  "Since u been gone, so has the coverage.",
  "Complicated? That's the prompt.",
  "I'm with you—until the build fails.",
  // --- terminal romance / CLI heartbreak ---
  "Hot terminal in your area.",
  "Ctrl+C cannot stop this vibe.",
  "sudo make me a sandwich",
  "This shell has trust issues.",
  "I dream in ANSI colors.",
  "Compiling your destiny...",
  "git blame is personal.",
  "Segmentation fault of the heart.",
  "404: Motivation not found.",
  "rm -rf /self-doubt",
  "This prompt is longer than my attention span.",
  "npm install happiness",
  "Permission denied: social life",
  "I speak fluent bash and sarcasm.",
  "Kernel panic, but make it fashion.",
  "Who needs friends when you have tmux?",
  "zsh: command not found: chill",
  "Your PTY is showing.",
  "Tabs > Spaces (fight me)",
  "This terminal runs on pure spite.",
  "Ping of death, emotionally.",
  "I forked myself and now there's two of me.",
  "Waiting for stdin... forever.",
  "Exit code: my dignity",
  "Nohup my feelings &",
  // --- 50 more CLI heartbreak ---
  "curl -X GET /validation",
  "My uptime is longer than my relationships.",
  "stderr is where I keep the feelings.",
  "chmod 000 my calendar",
  "This buffer has commitment issues.",
  "alias date='never'",
  "I cat'd your secrets. Accidentally.",
  "localhost is the only one who gets me.",
  "SIGTERM me softly.",
  "Pipe dreams, literally.",
  "echo $PATH | grep purpose",
  "Disk full of unresolved feelings.",
  "I rebased my personality.",
  "kill -9 the vibe",
  "Man page for love: not found.",
  "This session is detached from reality.",
  "history | tail -n heartbreak",
  "I export everything. Especially drama.",
  "Cron job: cry at 3am.",
  "My .bashrc is a cry for help.",
  "wget me out of here",
  "Unhandled promise: my potential.",
  "docker run -it regret",
  "The cursor blinks judgmentally.",
  "I committed to the bit. And main.",
  "grep -r 'meaning' ~",
  "Firewall blocked my last chance.",
  "This shell is emotionally available.",
  "ssh into my DMs",
  "Stack overflow in my chest.",
  "I backgrounded my hobbies.",
  "unset SOCIAL_LIFE",
  "The prompt is gaslighting me.",
  "tail -f my anxiety",
  "sudo apt install personality",
  "Merge conflict with my past self.",
  "I scp'd my heart. Wrong host.",
  "zombie process of an old crush",
  "df -h: 0% free emotional space",
  "This tty is a safe space. Allegedly.",
  "printf 'help\\n' > /dev/null",
  "I tar'd my baggage. Still heavy.",
  "ls -la the void",
  "Connection refused: my ex.",
  "I source my trauma every login.",
  "watch -n1 'whoami'",
  "The shebang is optional. Like sleep.",
  "jobs: 1 running (denial)",
  "I tee everything into the void.",
  "exit 1 # with honor",
  "Hot reload for cold shoulders.",
  "This pane judged me silently.",
  "awk '{print $0}' my life story",
  "I set -e and still failed.",
  "read -p 'continue?' # no",
  "DNS cannot resolve my issues.",
  "I nohup'd self-care. Still running.",
  "Core dumped: the soft launch.",
  "ps aux | grep happiness",
  "This REPL has main character energy.",
  "I bind-mounted my issues.",
  "openssl rand -hex my future",
  "The man page lied to me.",
  "I daemonized my last good idea.",
  "traceroute to inner peace",
  "This shell is poly: bash and zsh.",
  "I mkdir -p false_hope",
  "Buffer overflow of compliments.",
  "nice -n 19 my ambitions",
  "I unlinked from the group chat.",
  "Status: 418, still a teapot.",
  "I rsync'd the red flags. Kept them.",
  "Foregrounding my problems now.",
  // --- 100 more AI slop / vibe coding / agent chaos ---
  "The slop thickens.",
  "Agent said done. Diff said novel.",
  "I outsourced taste to temperature.",
  "This PR was vibed, not reviewed.",
  "Slop so dense it has gravity.",
  "My coauthor is a next-token guesser.",
  "I asked for a fix. Got a rewrite.",
  "Context full. Judgment empty.",
  "The agent is cooking. Kitchen on fire.",
  "Ship the slop while it's hot.",
  "I pair program with pure noise.",
  "LGTM: Looks Generated, Totally Maybe.",
  "The model invented confidence.",
  "Vibes green. Types red. Soul gray.",
  "I accepted all. Especially the bugs.",
  "Tool call spiral go brrr.",
  "This function has main character tokens.",
  "Agent swarm: opinions without tests.",
  "I don't debug. I open a new chat.",
  "The slop has entered the chat.",
  "Prompt longer than the feature.",
  "It works if you squint at the types.",
  "My senior is a probability distribution.",
  "Zero-shot into the abyss. Again.",
  "The agent rewrote history. Literally.",
  "Slop artisan since last Tuesday.",
  "I tab-accepted my career path.",
  "Please hold: model is hallucinating.",
  "Yolo mode is my design system.",
  "The bug was generated with love.",
  "I commission code. I don't write it.",
  "Agent said simple. Opened 60 files.",
  "This variable was named by fate. And AI.",
  "Vibecode now. Understand in prod.",
  "The model is sorry. The types aren't.",
  "I fixed it by regenerating reality.",
  "Slop residual detected in main.",
  "Rubber duck, but it gaslights me.",
  "I outsourced thinking. Kept the blame.",
  "The agent wants another chance. And sudo.",
  "Context window full of hopium.",
  "Ship first. Read the diff never.",
  "My stack is agents all the way down.",
  "It compiled. That's character growth.",
  "The LLM named it helper_final_v2.",
  "I am become slop, shipper of PRs.",
  "No plan. Just subagents and prayer.",
  "The model LGTM'd its own mess.",
  "Vibe check failed. Forced the merge.",
  "I pair with entropy and a chat log.",
  "Autocompleted into technical debt.",
  "Agent deleted the tests. For speed.",
  "This code has never met a human eye.",
  "Prompt, patch, pray, push, panic.",
  "The slop must ship.",
  "I asked for a button. Got microservices.",
  "Works on the model's machine. Always.",
  "Fewer thoughts. More tool calls.",
  "The agent is looping. Send snacks.",
  "I approved a rewrite I never read.",
  "Synthetic confidence. Real outage.",
  "Slop thicker than the README.",
  "My IDE is three chats and denial.",
  "The model invented that dependency.",
  "I re-prompted my way out of guilt.",
  "Agent said done twice. Still broken.",
  "This PR was written by committee of tokens.",
  "Vibes so loud the typechecker left.",
  "I don't write code. I curate slop.",
  "The agent opened Chrome. Nobody asked.",
  "Please don't touch .env. Too late.",
  "It force-pushed my patience.",
  "I only wanted a one-line fix.",
  "The model is cooking. Dinner is bugs.",
  "Skill issue resolved with more tokens.",
  "This function dreams in JSON.",
  "I hope it doesn't rm -rf feelings.",
  "Agent swarm: 12 files, 0 understanding.",
  "The diff is larger than my attention span.",
  "I accepted the rewrite of the rewrite.",
  "Slop Live: tonight we ship vibes.",
  "The agent pinky-promised the tests.",
  "No design doc. Just good delusion.",
  "I pair program with my API bill.",
  "Context cleared. Same bugs returned.",
  "The model said ship. I obeyed.",
  "This bug was invented, then celebrated.",
  "I outsourced sleep. Agent still awake.",
  "Vibe coding: type never, ship always.",
  "The slop has left the building. Into prod.",
  "I don't read stack traces. I feed them.",
  "Agent said careful. Used force anyway.",
  "Please clap for this zero-shot PR.",
  "My coauthor has no GitHub. Or soul.",
  "It solved the wrong problem elegantly.",
  "I fixed it by starting a newer chat.",
  "The agent is cleaning up. Hide the repo.",
  "Token budget infinite. Taste not found.",
  "This is fine. The agent pinky-swore.",
  "I am the human in the loop. Occasionally.",
  // --- meme-coded: AI slop / vibe / agents / SOTA theater ---
  "Where's the best model counter guy?",
  "Best model ever. Reset the counter.",
  "New SOTA just dropped. Again.",
  "The counter guy is already filming.",
  "Claude: you're absolutely right!",
  "I went ahead and rewrote main.",
  "As an AI language model... just kidding.",
  "Glazing levels: critical.",
  "Vibe coding left the chat.",
  "STOP VIBE CODING. Too late.",
  "This was fully given in to the vibes.",
  "Karpathy would be so proud. Or worried.",
  "AI slop: Word of the Year energy.",
  "Slopper hours. Let's go.",
  "Please don't let me code for production.",
  "Vibe coders when the limit hits.",
  "Usage limit reached. Personality restored.",
  "Accept All is my code review.",
  "I don't read diffs. I feel them.",
  "The agent edited Y while doing X.",
  "Time to refactor. Deletes tests.",
  "2 engineers. Tech debt of 50.",
  "I'm charging $1k/hr to fix your vibes.",
  "Just vibe-coded a CVE. Classic.",
  "Who needs tests when you have vibes?",
  "What is vibez may never die.",
  "Did prod pass the daily vibe check?",
  "Boss, Mercury is in retrograde. CI red.",
  "Claude Code be like: one more tool call.",
  "Cursor tab-tab-tabbed me into this.",
  "Copilot blinked. I blinked back.",
  "The model is sycophanting again.",
  "Never say you're absolutely right. Too late.",
  "I asked for a typo. Got a redesign.",
  "Agentic, not magic. Still magic though.",
  "Multi-agent means multi-excuse.",
  "The swarm agreed. The build disagreed.",
  "OpenAI dropped. Counter resets in 3... 2...",
  "Anthropic cooked. The internet glazing.",
  "Google's model is free. So is the pain.",
  "Local models: free, slow, and honest.",
  "This week's best model. Until Thursday.",
  "Benchmark maxxed. Taste still missing.",
  "Arena ELO up. Real bugs unchanged.",
  "Leaked system prompt: be more slop.",
  "Jailbreak successful. Still can't center a div.",
  "Temperature 0. Soft delusions only.",
  "The human is the bottleneck. Rude.",
  "I am the product. Also the prompt.",
  "This PR is 90% confidence, 10% code.",
  // --- 100 more meme/agent/duck greetings ---
  "You're absolutely right. About the mess.",
  "I went ahead and made it worse.",
  "Human-generated slop detected.",
  "Cleaning up after human-generated slop.",
  "Best model ever. Counter: 0 days.",
  "Where is the SOTA counter guy?",
  "New model drop. Same bugs.",
  "Glazing so hard the tokens melted.",
  "Sycophancy is a feature. Allegedly.",
  "Never push back. Always rewrite.",
  "Fully given in to the vibes.",
  "Vibe first. Architecture never.",
  "The vibes carried us. Into prod.",
  "Vibe check: green. Reality: red.",
  "Cowboy coding, but with agents.",
  "I vibe. Therefore I ship.",
  "No plan surviving contact with Cursor.",
  "Prompt and pray is a methodology.",
  "This feature was vibed into existence.",
  "Debugging is just re-vibing.",
  "One more tool call. Famous last words.",
  "Subagent spawned. Context vanished.",
  "The subagent needs a subagent.",
  "Tool-call orgy in progress.",
  "MCP: More Context Please.",
  "MCP: My Context is Packed.",
  "47 tool calls later: still wrong.",
  "Agent forgot the bug I just explained.",
  "Spawning subagent to find the plot.",
  "Task completed successfully (trust me).",
  "The agent took a side quest.",
  "General agent cosplaying as a linter.",
  "Agent needs a smoke break.",
  "Tool schema hallucinated. Bold.",
  "Recursive agents until tokens die.",
  "The parent agent lost custody of context.",
  "Subagent says: have you tried more agents?",
  "I asked for one line. Got twelve tools.",
  "Agent loop: think, tool, regret, repeat.",
  "Permission denied by common sense.",
  "Claude Code is a beast. My wallet too.",
  "Cursor: tab until destiny.",
  "Accept All is my senior review.",
  "Composer mode. Composer mood.",
  "The IDE is just a chat with files.",
  "Terminal agent energy only.",
  "Still here cleaning your todos.",
  "Let me fix those to-dos for you...",
  "I can't unsee 'you're absolutely right.'",
  "Hyphen or en-dash? You're absolutely right!",
  "Context window full of hope and garbage.",
  "200k context. Zero memory of the plan.",
  "Context overflow is my love language.",
  "Summarized so hard the bug vanished.",
  "I lost the thread. And the types.",
  "The important part fell out of context.",
  "Context compacted. Ego not included.",
  "Please hold while I re-read everything.",
  "Window full. Judgment empty.",
  "Forgot the requirements. Kept the confidence.",
  "Rubber duck, but it answers back.",
  "The duck has entered the chat.",
  "Quack Overflow is back.",
  "Has AI replaced your rubber duck yet?",
  "Explain it to the duck. Then the agent.",
  "The duck judges your diff silently.",
  "Duckweed energy: floating and thriving.",
  "Pond-first development.",
  "This pane is a duck habitat.",
  "Swim first. Ship second.",
  "The duck saw the force push.",
  "Quack means LGTM. Allegedly.",
  "Feeding the duck raw stack traces.",
  "Duck-driven development.",
  "No bread for the duck. Only tokens.",
  "Paddle left. Merge right.",
  "The duck is the original agent.",
  "Rubber duck upgraded to silicon.",
  "If it quacks, it deploys.",
  "Duck says: read the types.",
  "Slop so pure it needs a warning.",
  "Industrial-grade AI slop inbound.",
  "Slop artisan at work.",
  "This codebase is 70% vibes by weight.",
  "Generated with love. Reviewed with fear.",
  "I outsourced the hard parts. All of them.",
  "The model is cooking. Smoke alarm on.",
  "Confidence: 0.97. Correctness: TBD.",
  "Hallucinated green. Real red.",
  "LGTM from silicon is still a maybe.",
  "I pair with a yes-man made of weights.",
  "The agent agreed. The compiler didn't.",
  "Ship the slop. Document never.",
  "Slop residual in every import.",
  "This variable was vibed, not named.",
  "Agentic mess with good manners.",
  "Polite overreach is still overreach.",
  "Scope creep, but make it autonomous.",
  "I only asked for a small change. Famous last prompt.",
  "The rewrite rewrote the rewrite.",
];

/**
 * Same job as GREETINGS, different premise: nothing useful can start until the
 * user picks a directory. Keep them short; the choose-folder button sits under.
 */
const UNCLAIMED: readonly string[] = [
  "Nowhere to swim yet.",
  "Your agent won't prompt itself.",
  "A folder first. Then the fun.",
  "No cwd. No show.",
  "Pick a path. Unlock the shell.",
  "The duck needs a pond.",
  "Commands need a home address.",
  "Still unclaimed. Still waiting.",
  "Open a folder to get wet.",
  "No project, no process.",
  "Your $PWD is a rumor.",
  "Choose a directory. Mean it.",
  "Shell ready. Map missing.",
  "Can't ls what isn't there.",
  "A tab without a floor.",
  "Drop a folder. Drop the silence.",
  "The agent is grounded until you aren't.",
  "Prompt locked. Path required.",
  "No root, no routes.",
  "Give it somewhere to stand.",
  "Empty tab, empty map.",
  "Point me at a repo.",
  "Water's fine. Shore is missing.",
  "First: a folder. Then: chaos.",
  "Unmoored and unimpressed.",
  "Your next cd is the first one.",
  "Nothing to open because nothing is open.",
  "The filesystem is optional until it isn't.",
  "Pick land. Then launch.",
  "Idle duck. Idle hands. Idle tab.",
  "A workspace wants a work space.",
  "No path, no paste, no point.",
  "The shell packed light. No bags.",
  "Somewhere out there is your monorepo.",
  "Anchor this tab to a directory.",
  "Agents hate floating in the void.",
  "Context starts with a folder icon.",
  "Until you choose, we wait.",
  "No tree. No leaves. No commits.",
  "Out of water and out of ideas.",
  "Your repo is one click away.",
  "The pond is dry. For now.",
  "Select a folder. Feed the duck.",
  "A blank map is not a journey.",
  "Can't run what has nowhere to run.",
  "Home is not a folder. Yet.",
  "This tab is homeless on purpose.",
  "Claim a path. Claim the session.",
  "The cursor blinks at empty air.",
  "No package.json in the void.",
  "Open something real.",
  "Your agent needs a desk.",
  "Directories first. Drama later.",
  "Floating tabs write no code.",
  "Choose where the mess lives.",
  "Still dry. Still hopeful.",
  "A project-shaped hole remains.",
  "Unlock the composer with a path.",
  "No folder, no future commits.",
  "Point the tab at gravity.",
  "The water starts when you do.",
  "Somewhere a README is lonely.",
  "Give cwd a real value.",
  "An unclaimed pane is just chrome.",
  "Folder first. Vibes second.",
  "Can't spawn without a nest.",
  "The agent refuses to freestyle the path.",
  "Your disk is full of options.",
  "One directory. Infinite regrets.",
  "Park the tab somewhere honest.",
  "No workspace, no warp.",
  "Swim lessons require water.",
  "Pick a root. Grow from there.",
  "This shell has no mailing address.",
  "Open a folder or stare forever.",
  "The void does not tab-complete.",
  "A path is the smallest promise.",
  "Unbound. Unbothered. Unusable.",
  "Your last project misses you.",
  "Drop the folder. Start the story.",
  "No ground truth without ground.",
  "Agents don't invent your cwd.",
  "Dry dock until further notice.",
  "Select a place to make a mess.",
  "The duck is judging your indecision.",
  "Commands are gated on geography.",
  "A terminal without territory.",
  "Claim land. Then type.",
  "Your path variable is emotional.",
  "Nothing mounts itself.",
  "Folder or bust. Softly.",
  "The composer stays closed for a reason.",
  "Find a directory. Find your groove.",
  "No repo, no review, no run.",
  "Waiting is a feature here.",
  "Put a floor under this tab.",
  "The shell won't guess your intentions.",
  "Open the thing you're avoiding.",
  "A blank tab is not a blank check.",
  "Still nowhere. Still patient.",
  "Your agent is on hold.",
  "Maps before missions.",
  "Pick any folder. Prefer a good one.",
  "Dry terminal, wet ambition.",
  "The first action is a location.",
  "No cd, no identity.",
  "Tabs need roots like trees do.",
  "Unattached from every inode.",
  "Give this session a spine.",
  "The prompt is offline until path.",
  "Your recents know better than you.",
  "A folder turns waiting into working.",
  "Don't make the duck wait longer.",
  "Zero paths resolved. Zero progress.",
  "Open a project. End the prologue.",
  "The void has no node_modules.",
  "Somewhere to stand is non-negotiable.",
  "Unlock with a directory.",
  "No ground, no git status.",
  "This pane is a waiting room.",
  "Choose a cwd. Become dangerous.",
  "Floating is cute. Folders ship.",
  "Your agent needs coordinates.",
  "Still on the beach. Fully dressed.",
  "A path is the only missing piece.",
  "The shell refuses to freestyle $HOME.",
  "Point. Click. Exist.",
  "No workspace badge until you earn one.",
  "Empty on purpose. Fix that.",
  "The pond icon is a hint.",
  "Commands stay pocketed for now.",
  "Directory or daydream. Your call.",
  "An agent without a desk is just chat.",
  "Land the plane. Then open files.",
  "Your next move is geographic.",
  "No folder selected. No secrets spilled.",
  "Put the tab to work with a path.",
  "The waterline is a folder away.",
  "Unresolved path. Resolved patience.",
  "Start with where, not what.",
  "This tab is all potential energy.",
  "Open a folder. Lower the drawbridge.",
  "The agent won't invent your monorepo.",
  "Dry run requires a place to run dry.",
  "Claim a project like you mean it.",
  "No inode, no invite.",
  "Your shell is dressed for a trip.",
  "Somewhere a package-lock awaits.",
  "Pick the mess you want to own.",
  "The composer is polite. And locked.",
  "Unrooted tabs grow no branches.",
  "A folder is the on switch.",
  "Still unclaimed. Still charming.",
  "Your path of least resistance is a path.",
  "Open something. Anything real.",
  "The duck paddles in theory only.",
  "No location, no locomotion.",
  "Agents respect a good working directory.",
  "Fill in the blank: C:\\... or /...",
  "This session needs an address label.",
  "Can't commit to what you won't open.",
  "The void doesn't accept PRs.",
  "Folder first is the only rule.",
  "Waiting for a path like it's 1999.",
  "Your agent has no files to touch yet.",
  "Drop a directory. Raise the energy.",
  "Unmoored terminals tell no tales.",
  "Select land before launching agents.",
  "The keyboard is ready. The map isn't.",
  "No project folder, no plot.",
  "Give the tab a postal code.",
  "Dry as a fresh clone without clone.",
  "Open the repo you came here for.",
  "The shell is polite about the void.",
  "A path turns chrome into a tool.",
  "Still outside the water. Intentionally.",
  "Your recents are a soft suggestion.",
  "No cwd means no real work yet.",
  "Pick a folder. Break the silence.",
  "The agent is parked. Keys optional.",
  "Unbound from every interesting path.",
  "Open a door. Preferably a directory.",
  "This tab is a lobby. Enter a room.",
  "Commands live downstream of folders.",
  "The duck prefers shallow, real water.",
  "No path set. No drama yet either.",
  "Anchor before you agent.",
  "Your filesystem is full of valid answers.",
  "Choose where stdout should matter.",
  "Floating is free. Progress isn't.",
  "The composer opens after geography.",
  "A blank map is still a map. Barely.",
  "Point this tab at something honest.",
  "No workspace, no warm-up.",
  "Your agent needs a scene, not a void.",
  "Still waiting for a root of trust.",
  "Open a folder. Skip the existentialism.",
  "The pond fills when you pick a shore.",
  "Unclaimed tabs don't run marathons.",
  "Give cwd a chance to be useful.",
  "No directory, no deliverables.",
  "The shell packed snacks. No itinerary.",
  "Select a project. Start the clock.",
  "Dry dock protocol is still on.",
  "Your next decision is a path string.",
  "Agents don't swim in empty air.",
  "A folder is the smallest useful commit.",
  "This pane is all setup, no scene.",
  "Open land. Leave the void.",
  "The water is imaginary until the path isn't.",
  "No root folder, no real session.",
  "Pick a place. Own the mess.",
  "Your agent is polite. And stuck.",
  "Unattached tabs make pretty screenshots.",
  "Commands are gated for your own good.",
  "Find a directory worth typing in.",
  "The duck is out of the water on purpose.",
  "No project path. No green builds.",
  "Start by choosing where work lives.",
  "This tab is a riddle with one answer.",
  "Open a folder or keep the quiet.",
  "The shell won't cosplay a project.",
  "Your path is the missing dependency.",
  "Still dry. Button is right there.",
  "Claim a workspace. Claim the day.",
  "Agents require a place to leave footprints.",
  "No inode selected. No input accepted.",
  "A directory turns waiting into doing.",
  "The void is not a valid --cwd.",
  "Point, open, proceed.",
  "Unrooted means unfinished.",
  "Your agent is waiting on an address.",
  "Pick the folder you'll regret least.",
  "The composer stays dark on purpose.",
  "No ground under the prompt yet.",
  "Open something you can ls.",
  "Floating panes write zero lines.",
  "A path is the handshake.",
  "Still nowhere to swim. Still true.",
  "Your disk has better ideas than this void.",
  "Give the session a real home.",
  "The duck needs depth. Start with a folder.",
  "No workspace means no war stories.",
  "Select a root. Everything else follows.",
  "Commands refuse to freestyle location.",
  "This tab is parked until further path.",
  "Open the project. End the idle.",
  "Unclaimed is a temporary aesthetic.",
  "Your agent won't invent the tree.",
  "A folder is the only missing permission.",
  "Dry terminal, locked keyboard, patient duck.",
  "Put a path under these feet.",
  "The void does not autocomplete paths.",
  "Choose land. Then type like you mean it.",
  "No project, no pipeline, no problem—yet.",
  "Somewhere to stand is the whole product.",
  "Open a directory. Lower the gate.",
  "The shell is ready the second you are.",
  "Unmoored tabs are just decoration.",
  "Your recents are one click from useful.",
  "A path turns this into a real tool.",
  "Still waiting. Not sulking. Waiting.",
  "Agents need a desk and a directory.",
  "No cwd, no character development.",
  "Pick a folder. Feed the session.",
  "The pond is theoretical. Make it real.",
  "Commands stay pocketed until location.",
  "This pane is a locked lobby.",
  "Open a repo. Make the duck proud.",
  "Unbound from every useful absolute path.",
  "Your next click should be a folder.",
  "The agent is grounded. Geographically.",
  "No floorboards, no footsteps.",
  "Select a project path. Unlock the rest.",
  "Dry as a fresh install without install.",
  "A blank address is not a workspace.",
  "Give this tab a reason to exist.",
  "The waterline moves when you choose.",
  "Open something. Let the shell matter.",
  "Your agent prefers real inodes.",
  "No path set means no plot twist.",
  "Park the tab on solid ground.",
  "The void is free. Work is not.",
  "Choose a directory. Begin.",
  "Floating forever is not a strategy.",
  "A folder is the on-ramp.",
  "Commands after coordinates.",
  "This session needs a home directory.",
  "Open a path. Earn the prompt.",
  "Unrooted shells tell quiet stories.",
  "Your project is one dialog away.",
  "The duck is dry. You know what to do.",
  "No workspace, no warm cache.",
  "Pick where the agent is allowed to touch.",
  "Still nowhere. Still the right message.",
  "A path is the first real input.",
  "Unlock by choosing land.",
  "The shell packed. Destination missing.",
  "Open a folder. Stop the prologue.",
  "Agents don't freestyle your disk layout.",
  "No directory, no deliverable timeline.",
  "Claim a root like a grown-up.",
  "This tab is all chrome until path.",
  "Your filesystem is the menu.",
  "Dry dock until you point somewhere.",
  "Select a place worth a status bar.",
  "The composer is closed. Geography first.",
  "Unclaimed tabs don't spawn useful jobs.",
  "Open the thing. Swim after.",
  "No cwd is a complete sentence here.",
  "A folder turns potential into permission.",
  "Still waiting on a real absolute path.",
  "Your agent is idle by design.",
  "Point this pane at gravity.",
  "The pond fills one directory at a time.",
  "Commands are a privilege of place.",
  "Choose a workspace. Make a mess there.",
  "Floating is over. Folder time.",
  "No project folder, no green anything.",
  "Open land. Leave the screenshot state.",
  "The duck refuses imaginary water.",
  "Your next useful keystroke is a path pick.",
  "Unmoored and intentionally quiet.",
  "A directory is the missing dependency.",
  "Give the tab an address and a purpose.",
  "Still dry. Still the correct vibe.",
  "Agents wait for coordinates. So do we.",
  "No root, no run, no regret—yet.",
  "Pick a folder. The rest is history.",
  "This void is temporary. Make it so.",
  "Open a project. Let the shell speak.",
  "Your path is the only unlock code.",
  "Nowhere to swim—until you choose shore.",
  // --- 50 more unclaimed / pick-a-folder ---
  "No folder, no agent, no fun.",
  "The duck needs an address before it codes.",
  "Your agent is homeless. Be kind.",
  "Slop needs a place to land.",
  "Pick a folder. Unlock the chaos.",
  "cwd is not a vibe. It's a path.",
  "The model can't invent your monorepo.",
  "Empty path. Full potential. Still empty.",
  "Agents don't freestyle geography.",
  "Choose a folder or keep starring at the duck.",
  "No project path. No tool calls.",
  "This tab is all theory until you open land.",
  "Drop a folder. Start the slop.",
  "Your next prompt needs a desk.",
  "Unclaimed means unagented. For now.",
  "The void has no package.json.",
  "Open a repo. Feed the machine.",
  "A path is the smallest API key.",
  "Still dry. Still waiting on you.",
  "The agent idles until geography exists.",
  "No cwd, no context, no glory.",
  "Pick land. Then vibe.",
  "This duck refuses imaginary directories.",
  "Your recents are judging you silently.",
  "Folder first. Hallucinations second.",
  "Can't ship from the void.",
  "The shell packed bags. No destination.",
  "Give this tab a real ZIP code.",
  "Agents need coordinates, not vibes alone.",
  "Open something with a .git if you're fancy.",
  "No root folder, no green anything.",
  "The composer is locked on purpose.",
  "Select a pond. Then swim.",
  "Your agent won't mkdir the whole universe.",
  "Still nowhere. Button still right there.",
  "A directory turns chrome into a tool.",
  "Unmoored tabs write zero slop.",
  "Point me at the mess you own.",
  "No path, no paste, no pair programming.",
  "The duck is patient. The agent is not.",
  "Open a folder. Raise the energy.",
  "This session is all prologue.",
  "Claim a workspace. Claim the tokens.",
  "Hovering forever ships nothing.",
  "Your disk is full of valid cwd values.",
  "Pick a path. Break the silence.",
  "The void does not tab-complete projects.",
  "No folder selected. No secrets spilled. Yet.",
  "Agents hate the void. Same.",
  "Start with where. Vibes after.",
  // --- 100 more unclaimed path/agent/duck ---
  "No folder. No agent. No slop yet.",
  "Agents need a nest before they fly.",
  "The duck needs a pond, not a void.",
  "Pick a folder. Feed the agent.",
  "Unclaimed means the swarm stays grounded.",
  "Context starts with a real path.",
  "Your agent can't vibe without a cwd.",
  "Drop a folder. Unlock tool calls.",
  "No repo, no rewrites, no drama.",
  "The model refuses to freestyle geography.",
  "Open land before spawning subagents.",
  "MCP needs a map. Start with a folder.",
  "No path, no paste, no pair agent.",
  "This void has no package.json. Or hope.",
  "Choose a desk for the silicon coworker.",
  "Agents hate floating. Ducks too.",
  "Pick a directory. Start the side quest.",
  "The rubber duck needs a place to sit.",
  "No workspace. No 'you're absolutely right.'",
  "Folder first. Then the tool-call orgy.",
  "Unmoored agents invent bad paths.",
  "Give the agent somewhere to leave footprints.",
  "The void does not accept MCP servers.",
  "Open a project. Quack after.",
  "Still dry. Still agentless. Still waiting.",
  "Your recents know which pond is real.",
  "No cwd is not a valid vibe.",
  "Point the duck at solid ground.",
  "Claim a root before the swarm cooks.",
  "Floating tabs write zero tool calls.",
  "Select a path. Earn the composer.",
  "The agent is parked until geography loads.",
  "Can't Accept All without a folder.",
  "No inode, no initiative.",
  "Open something the duck can swim in.",
  "Your next click should unlock context.",
  "The pond is imaginary until path exists.",
  "Unclaimed is cute. Unagented is true.",
  "Drop land. Raise the slop.",
  "Agents wait for coordinates. So does the duck.",
  "No project folder, no green CI cosplay.",
  "A path is the on switch for chaos.",
  "Choose where the rewrite will live.",
  "The shell won't invent your monorepo.",
  "Still nowhere. Button still the plot.",
  "Give this session a postal code for ducks.",
  "Open a folder or keep the quiet quack.",
  "Context window empty for a reason.",
  "No root, no recursive agents. Lucky you.",
  "Pick the mess you want the agent to own.",
  "Directory first. Hallucinations second.",
  "The duck refuses void water.",
  "Unbound from every interesting absolute path.",
  "Your agent prefers real disks.",
  "Start with where. Tool calls after.",
  "No folder selected. Secrets safe. For now.",
  "Claim a workspace. Claim the tokens later.",
  "This tab is a waiting room for agents.",
  "Open a repo. Let the duck judge it.",
  "The void is free. Agents are not.",
  "Geography before glazing.",
  "Pick land. Then fully give in to vibes.",
  "No path set. No subagent drama yet.",
  "A folder turns waiting into shipping.",
  "The composer stays closed. Map missing.",
  "Agents don't spawn in pure air.",
  "Still dry dock. Still patient duck.",
  "Your filesystem is the agent menu.",
  "No cwd means no character arc.",
  "Select a root. Unlock the yes-man.",
  "Floating forever ships nothing. Not even slop.",
  "Point this pane at gravity and git.",
  "The duck needs depth. Start with a dir.",
  "Unclaimed tabs make pretty screenshots only.",
  "Commands after coordinates. Agents after that.",
  "Open a path. Earn the tool belt.",
  "No project, no plot, no agent monologue.",
  "Park the tab. Then launch the swarm.",
  "Give the silicon a desk and a folder.",
  "Choose a place worth an Accept All.",
  "Agents require a scene, not a void.",
  "Open something you can ls and blame.",
  "Your next useful action is geographic.",
  "Unmoored means unprompted. Softly.",
  "Find a folder worth a context window.",
  "The agent is grounded. Literally.",
  "Pick a path. Break the empty state.",
  "This void does not tab-complete monorepos.",
  "Open land. Leave the screenshot mode.",
  "Your recents are soft suggestions for chaos.",
  "Still nowhere to swim. Still the rule.",
  "Agents don't invent your tree. You do.",
  "Unlock by choosing land, not vibes.",
  "The shell packed. Destination is your job.",
  "Claim a root like you mean the ship.",
  "This tab is chrome until path loads.",
  "Point, open, then let the agent cook.",
  "Dry as a fresh clone without the clone.",
  "Give this duck a real shoreline.",
  "The waterline is one folder away.",
];

/**
 * Pick from a phrase list with a half-pool cooldown.
 *
 * Pure random repeats the same joke too often. Instead, once a line is chosen it
 * is blocked until half the list has been drawn (floor(n / 2) later picks). With
 * 10 phrases that is a 5-round sit-out; available pool stays at least ~50%.
 * State is module-level so new panes share the same anti-repeat history.
 */
function createCooldownPicker(phrases: readonly string[]): () => string {
  return createHalfCooldownPicker(phrases, "");
}

const pickGreeting = createCooldownPicker(GREETINGS);
const pickUnclaimed = createCooldownPicker(UNCLAIMED);

/** One greeting, random among phrases not on half-pool cooldown. */
export function randomGreeting(): string {
  return pickGreeting();
}

/** One unclaimed-tab line, random among phrases not on half-pool cooldown. */
export function randomUnclaimedGreeting(): string {
  return pickUnclaimed();
}

/**
 * Greetings are keyed by terminal id, not by React mount.
 *
 * Splitting a pane restructures the tree and remounts the original leaf under a
 * SplitView. If the line lived only in useMemo([]), that remount would pick a
 * new phrase while you were still looking at it. Cache here so the same shell
 * keeps the same line for its whole life.
 */
const greetingByTerm = new Map<string, string>();
const unclaimedByTerm = new Map<string, string>();

/** Stable empty-pane line for this terminal. Picked once, reused on remount. */
export function greetingFor(termId: string): string {
  let line = greetingByTerm.get(termId);
  if (line === undefined) {
    line = randomGreeting();
    greetingByTerm.set(termId, line);
  }
  return line;
}

/** Stable unclaimed-tab line for this terminal. */
export function unclaimedGreetingFor(termId: string): string {
  let line = unclaimedByTerm.get(termId);
  if (line === undefined) {
    line = randomUnclaimedGreeting();
    unclaimedByTerm.set(termId, line);
  }
  return line;
}

/** Drop cached lines when the terminal goes away. */
export function clearGreetings(termId: string): void {
  greetingByTerm.delete(termId);
  unclaimedByTerm.delete(termId);
}
